project:
  type: website
publishDir: "../kaitlynschmeling.github.io"
website:
  title: "Blog"
  description: "A blog about the best baseball player"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kschmeling
      - icon: twitter
        href: https://twitter.com/kaitlynschmeling
favicon: logo.png

format:
  html:
    theme: cosmo
    light: litera
    dark: cyborg
    css: styles.css
    



